trigger:
 branches:
   include:
     - main
       feature/*

pool: agent_vinod

variables:
  service connection: 'multi-ttriggersc'
  workdir: '$(System.DefaultWorkingDirectory)/Environment/Dev'

steps:
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(workdir)
    backendServiceArm: $(service connection)
    backendAzureRmStorageAccountName: 'akkcstorageaccount007'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'vinod.tfstate'

- task: TerraformTask@5
  displayName: terrfaorm Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(workdir)

- task: TerraformTask@5
  displayName: Terraform Format
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: $(workdir)
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: $(service connection)

- task: TerraformTask@5
  displayName: terraform plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(workdir)
    environmentServiceNameAzureRM: $(service connection)



- task: TerraformTask@5
  displayName: terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(workdir)
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: $(service connection)
  