trigger:
  branches:
    include:
      - main
      - feature/*

variables:
  service_connection: 'multi-ttriggersc'
  workdir: '$(System.DefaultWorkingDirectory)/Environment/Dev'

jobs:
- job: Terraform_Execution
  displayName: 'Terraform Init/Plan (and Apply for main)'
  pool: agent_vinod

  steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(workdir)
        backendServiceArm: $(service_connection)
        backendAzureRmStorageAccountName: 'akkcstorageaccount007'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'vinod.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(workdir)

    - task: TerraformTask@5
      displayName: Terraform Format
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: $(workdir)
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: $(service_connection)

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(workdir)
        environmentServiceNameAzureRM: $(service_connection)

- job: Manual_Approval
  displayName: 'Manual Approval before Apply'
  dependsOn: Terraform_Execution
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  pool: server  # Server-side job, required for ManualValidation

  steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Approve to proceed with Terraform Apply.'
        onTimeout: 'reject'
        timeout: '1d'
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'dkc.hcl@gmail.com'
        approvers: 'akkc01'


- job: Terraform_Apply
  displayName: 'Terraform Apply'
  dependsOn: Manual_Approval
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  pool: agent_vinod

  steps:
    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(workdir)
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: $(service_connection)
