# .github/workflows/test-pipeline.yml

name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  echo-job:
    runs-on: [self-hosted, Windows, X64]  # Make sure labels match exactly
    steps:
      - name: Say Welcome
        run: echo "welcome bro!"
