name: Terraform Azure CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform-initplan:
    name: Terraform Init/Validate/Plan
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # ya jo bhi version tu use kar raha hai

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/tfplan

  terraform-apply:
    name: Terraform Apply
    runs-on: self-hosted
    needs: terraform-plan

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: infra/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
